### ISSUE TITLE
Shadow Board Page Content 

### ISSUE THREAD

**Issue by DarrenKirmond** [DarrenKirmond/georgekk#6]
Hi George,

Please can you give me the text and pictures you would like to display on these pages? You can upload them to this issue by adding them to a comment below. Let me know if you need any help.

Many thanks

**Comment by DarrenKirmond** [comment]
![DSC_0026-1024x680](https://user-images.githubusercontent.com/33051801/204597085-b866d80d-3cc2-42b8-b0f5-f8dca77c1205.jpg)

**Comment by GeorgeKK2022** [comment]
Shadow Boards are an excellent way to keep your shop floor or workshop in order.
They can be used as a Cleaning stations, Machine’s change over parts, Tool boards,
Information boards etc.
[Click here for CLEANING STATIONS](http://www.georgekk.co.uk/shadow-boards/cleaning-stations/)
Full implementation of the 5S.  
BE practical
LOOK professional – The 5S
•	 Free Design and Branding.
•	 Set-up and Fabrication.
•	 Laminated for EXTRA strength and protection.
•	 Aluminium Composite or PVC PALIGHT.
All made with attention to detail: high quality products for durability and scratch resistance.
